name: ToCookQuickly
main: TCQ\Main
version: 0.0.5
api: [2.0.0]
load: POSTWORLD
author: gigantessbeta
authors: [PMplugMaker-Team, opkiler22789]
website: https://github.com/PMpluginMaker-Team/ToCookQuickly
